name: Java CI with Gradle

concurrency: 
  group: "build-1.17"
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '*.md'
      

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
       fail-fast: false
       matrix:
         java: [ '16', '16.0.1' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.Java }}
        distribution: 'zulu'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Remove *-dev.jar
      run: rm ./build/libs/*-dev.jar
    - uses: "marvinpinto/action-automatic-releases@latest"
      if: ${{ matrix.Java == '16' }}
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-1.17"
          prerelease: false
          title: "1.17 Build"
          files: |
            ./build/libs/*.jar
