name: Java CI with Gradle

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '16', '16.0.1' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.Java }}
        distribution: 'zulu'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pull-request-build
        path
